apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-trace-debug
  labels:
    app: dd-trace-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-trace-debug
  template:
    metadata:
      labels:
        app: dd-trace-debug
    spec:
      containers:
      - name: dd-trace-debug
        image: dd-trace-debug:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENV
            value: dev
          - name: DD_SERVICE
            value: dd-trace-debug
